require_relative '../hello'
require_relative '../temperature'
require_relative '../calculator'
require_relative '../simon_says'
require_relative '../pig_latin'
require_relative '../book_titles'
require_relative '../timer'